// Run with Node.js; set NODE_PATH to the directory containing Playwright.
const { chromium } = require('playwright');
const { pathToFileURL } = require('url');
const path = require('path');
const fs = require('fs');
const root = path.resolve(__dirname, '..');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'msedge',args:['--disable-gpu']});
  const context = await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const page = await context.newPage();
  const errors = [], broken = [], overflow = [];
  page.on('pageerror',e=>errors.push(e.message));
  const base = pathToFileURL(path.join(root,'index.html')).href;
  const admin = pathToFileURL(path.join(root,'admin.html')).href;
  await page.goto(base);
  await page.screenshot({path:path.join(__dirname,'学生端-首页.png'),fullPage:true});
  const studentRoutes=['home','activity','activity/detail/1','activity/publish','activity/my-signup','idle','idle/detail/1','idle/publish','idle/appointments','lostfound','lostfound/detail/1','lostfound/publish','lostfound/claims','social','social/publish','notice','notice/detail/1','message','chat','chat/1','ai/chat','ai/code','ai/wrong','profile','user/1','search','login','register','maintenance','sitemap'];
  for(const r of studentRoutes){await page.goto(base+'#/'+r);await page.waitForTimeout(40);const check=await page.evaluate(()=>({empty:document.querySelector('#app').innerText.length<30,overflow:document.documentElement.scrollWidth>innerWidth+1,broken:[...document.images].filter(i=>!i.hidden&&i.getAttribute('src')&&i.complete&&i.naturalWidth===0).map(i=>i.src)}));if(check.empty)errors.push('Empty route '+r);if(check.overflow)overflow.push(r);broken.push(...check.broken);}
  await page.goto(base+'#/activity/detail/1');
  await page.getByRole('button',{name:'收藏',exact:true}).click();
  await page.getByRole('button',{name:'已收藏',exact:true}).waitFor();
  await page.getByRole('button',{name:'立即报名',exact:true}).click();
  await page.locator('dialog [name=contact]').fill('站内私信');
  await page.getByRole('button',{name:'提交报名',exact:true}).click();
  await page.getByRole('button',{name:'模拟审核通过',exact:true}).click();
  await page.getByRole('button',{name:'活动签到',exact:true}).click();
  await page.locator('dialog [name=code]').fill('WT2026');
  await page.getByRole('button',{name:'确认签到',exact:true}).click();
  await page.getByText('签到完成',{exact:true}).waitFor();
  await page.goto(base+'#/idle/detail/1');
  await page.getByRole('button',{name:'预约互换',exact:true}).click();
  await page.locator('dialog [name=intent]').fill('用羽毛球拍互换');
  await page.getByRole('button',{name:'提交预约',exact:true}).click();
  await page.getByRole('button',{name:'模拟对方同意',exact:true}).click();
  await page.getByRole('button',{name:'确认互换完成',exact:true}).click();
  await page.getByRole('button',{name:'留下评价',exact:true}).click();
  await page.locator('dialog [name=review]').fill('沟通顺利，互换完成');
  await page.getByRole('button',{name:'确认提交',exact:true}).click();
  await page.getByRole('button',{name:'查看评价',exact:true}).waitFor();
  await page.goto(base+'#/lostfound/detail/1');
  await page.getByRole('button',{name:'申请认领',exact:true}).click();
  await page.locator('dialog [name=proof]').fill('银色外壳，装有课程资料');
  await page.getByRole('button',{name:'确认提交',exact:true}).click();
  await page.getByRole('button',{name:'模拟审核通过',exact:true}).click();
  await page.getByRole('button',{name:'确认领取',exact:true}).click();
  await page.getByText('物归原主',{exact:true}).waitFor();
  await page.goto(base+'#/activity/publish');
  await page.locator('[name=title]').fill('原型测试活动');
  await page.locator('[name=description]').fill('测试发布与编辑流程');
  await page.locator('[name=location]').fill('校园广场');
  await page.getByRole('button',{name:'提交审核',exact:true}).click();
  await page.getByText('原型测试活动',{exact:true}).waitFor();
  await page.getByRole('link',{name:'编辑',exact:true}).click();
  await page.locator('[name=title]').fill('原型测试活动已编辑');
  await page.getByRole('button',{name:'提交审核',exact:true}).click();
  await page.getByText('原型测试活动已编辑',{exact:true}).waitFor();
  await page.goto(base+'#/ai/chat');
  await page.getByRole('button',{name:'讲解乘积求导法则',exact:true}).click();
  await page.getByText('【预设演示回答】',{exact:false}).waitFor();
  await page.goto(base+'#/ai/wrong');
  await page.getByRole('button',{name:'开始复习',exact:true}).first().click();
  await page.getByRole('button',{name:'我已掌握',exact:true}).click();
  await page.goto(base+'#/chat');
  await page.locator('[name=message]').fill('<script>演示输入</script>');
  await page.getByRole('button',{name:'发送',exact:false}).click();
  await page.getByText('<script>演示输入</script>',{exact:true}).waitFor();
  await page.goto(base+'#/search?q='+encodeURIComponent('音乐'));
  if(!await page.getByText('落日之后，一起听见青春',{exact:true}).count())errors.push('Search failed');
  const adminRoutes=['dashboard','user','audit/activity','audit/idle','audit/lostfound','audit/post','content','ai/audit','report','notice','notice/edit','notice/edit/1','ai/config','ai/logs','system/config','system','login','sitemap'];
  for(const r of adminRoutes){await page.goto(admin+'#/'+r);await page.waitForTimeout(40);const check=await page.evaluate(()=>({empty:document.querySelector('#app').innerText.length<30,overflow:document.documentElement.scrollWidth>innerWidth+1}));if(check.empty)errors.push('Empty admin route '+r);if(check.overflow)overflow.push('admin/'+r);}
  await page.goto(admin+'#/audit/activity');
  await page.getByRole('button',{name:'通过',exact:true}).first().click();
  await page.getByText('已通过',{exact:true}).first().waitFor();
  await page.getByRole('button',{name:'驳回',exact:true}).first().click();
  await page.locator('dialog [name=reason]').fill('请补充活动说明');
  await page.getByRole('button',{name:'确认驳回',exact:true}).click();
  await page.getByText('已驳回',{exact:true}).first().waitFor();
  await page.goto(admin+'#/dashboard');
  await page.screenshot({path:path.join(__dirname,'管理端-数据总览.png'),fullPage:true});
  await page.goto(base+'#/home');
  await page.getByRole('button',{name:'切换明暗主题'}).click();
  await page.screenshot({path:path.join(__dirname,'学生端-深色模式.png'),fullPage:true});
  await page.getByRole('button',{name:'切换明暗主题'}).click();
  await page.setViewportSize({width:390,height:844});
  for(const r of studentRoutes){await page.goto(base+'#/'+r);await page.waitForTimeout(40);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))overflow.push('mobile/'+r);}
  for(const r of adminRoutes){await page.goto(admin+'#/'+r);await page.waitForTimeout(40);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))overflow.push('mobile/admin/'+r);}
  await page.goto(base+'#/home');
  await page.screenshot({path:path.join(__dirname,'学生端-手机首页.png'),fullPage:true});
  await page.getByRole('button',{name:'切换导航'}).click();
  await page.locator('.sidebar.open').waitFor();
  const report={checkedAt:new Date().toISOString(),desktop:'1440 × 1100',mobile:'390 × 844',routeCount:studentRoutes.length+adminRoutes.length,studentRoutes,adminRoutes,errors,brokenImages:[...new Set(broken)],overflow,flows:['收藏','活动报名 / 审核 / 签到','闲置预约 / 完成 / 评价','失物认领 / 确认','发布 / 编辑','AI 示例回答','错题复习','私信发送与 HTML 转义','搜索','管理员审核 / 驳回','主题切换','手机导航']};
  fs.writeFileSync(path.join(__dirname,'browser-report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
  await browser.close();
  if(errors.length||broken.length||overflow.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1);});
